services:
  stirling-pdf:
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:2.10.1@sha256:950c596db26e0764f642def2fd4f9ee904ff2ac16d83fe621ff731b771d9b385
    container_name: stirling-pdf
    restart: unless-stopped
    networks:
      - traefik_external_public_web
    ports:
      - '35037:8080'
    volumes:
      - $DOCKER_DATA/stirling-pdf/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - $DOCKER_DATA/stirling-pdf/extraConfigs:/configs
      - $DOCKER_DATA/stirling-pdf/customFiles:/customFiles/
      - $DOCKER_DATA/stirling-pdf/logs:/logs/
      - $DOCKER_DATA/stirling-pdf/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - LANGS=zh_CN
    labels:
      # --- labelgate --- #
      # labelgate.tunnel.pdf.hostname: pdft.${DOMAIN_HSC}
      # labelgate.tunnel.pdf.service: http://stirling-pdf:8080
      # labelgate.tunnel.pdf.access: test-policy
      # labelgate.access.test-policy.policy.include.country: "JP"
      # labelgate.access.test-policy.policy.decision: "allow"
      #---
      traefik.enable: true
      traefik.public: true
      traefik.docker.network: traefik_external_public_web
      traefik.http.routers.pdfttt.rule: Host(`pdft.${DOMAIN_CC}`)
      traefik.http.routers.pdfttt.entrypoints: cf, http
      traefik.http.services.pdfttt.loadbalancer.server.port: 8080
      traefik.http.routers.pdfttt.service: pdfttt

networks:
  traefik_external_public_web:
    external: true