version: '3.5'
services:
  drawio:
    image: jgraph/drawio:29.7.11@sha256:f75a81c8a445456244218138ab1919b10ea946057f5844f8a56b270572731314
    container_name: drawio
    restart: unless-stopped
    ports:
      - 36711:8080
      #- 8443:8443
    #environment:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s