version: '3.5'
services:
  drawio:
    image: jgraph/drawio:30.0.2@sha256:b87c521e53760fa33916182d96bc35989384b03b1b40d9a493bbdc3677a66b51
    container_name: drawio
    restart: unless-stopped
    ports:
      - 36711:8080
      #- 8443:8443
    #environment:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s