services:
  forgejo-int:
    image: codeberg.org/forgejo/forgejo:15.0.2@sha256:db04c7114b656f896e206ba3873fe8d3a7adf2daa44907037f0274f4ba653fb9
    container_name: forgejo-int
    #user: 5000:5000 rootless only
    environment:
      - USER_UID=5000
      - USER_GID=5000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=forgejo-postgres:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo-int
      #- FORGEJO__database__PASSWD=${FORGEJO_INT_DB_PASSWORD}
    restart: always
    networks:
      - default
      - traefik-poecilia_local_web
    volumes:
      - $DOCKER_DATA/forgejo-int/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "53110:3000"
      - "11222:22"
    labels:
      homepage.group: Dev
      homepage.name: Forgejo Internal
      homepage.icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/forgejo.png
      homepage.href: "https://git.${DOMAIN_INT}"
      #homepage.widget.type: gitea
      #homepage.widget.url: https://git.${DOMAIN_INT}
  forgejo-postgres:
    image: postgres:14@sha256:d462928b1898dd74b749ef486797968828c1e7fc9befb5e5ca03a33bfbc32d64
    container_name: forgejo-postgres
    restart: always
    command:
      - "postgres"
      - "-c"
      - "full_page_writes=off"
    environment:
      - POSTGRES_DB=forgejo
      - POSTGRES_USER=forgejo-int
      - POSTGRES_PASSWORD=${FORGEJO_INT_DB_PASSWORD}
    networks:
      - default
    volumes:
      - $DOCKER_DATA/forgejo-int/postgres:/var/lib/postgresql/data

networks:
  default:
    external: false
  traefik-poecilia_local_web:
    external: true
