services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.37.1@sha256:f3b9c936abb8bf49ab4340e6d8daa458b378f2bfe238d60bda398214e844d58d
    container_name: zerobyte
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "34096:4096"
    environment:
      - TZ=Asia/Tokyo # Set your timezone here
      - BASE_URL=https://zerobyte.${DOMAIN_INT} # Change this to your actual URL (use https:// for secure cookies)
      - APP_SECRET=${ZEROBYTE_APP_SECRET} # Generate your own secret with `openssl rand -hex 32`
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_DATA}/zerobyte:/var/lib/zerobyte
      - ${DOCKER_DATA}/zerobyte/rclone/config:/root/.config/rclone
      # data 
      - ${PATH_BACKUP}:${PATH_BACKUP}:ro
      - ${PATH_PV}:${PATH_PV}:ro
    labels:
      traefik.enable: true
      traefik.http.routers.zerobyte.rule: Host(`zerobyte.${DOMAIN_INT}`)
      traefik.http.routers.zerobyte.entrypoints: websecure
      traefik.http.routers.zerobyte.service: zerobyte
      traefik.http.services.zerobyte.loadbalancer.server.port: 34096
      kop.namespace: poecilia
