services:
  nixosrl-kop-poecilia:
    #image: "ghcr.io/jittering/traefik-kop:latest"
    image: channinghe/traefik-kop:test@sha256:cce0beece50bb50a428568f7ce4196b43bb65ddb6121631bf0ef59ecf0ac68f9
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=${IP_POECILIA}:6379"
      #- "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=nixos-rl"
      - "BIND_IP=${IP_NIXOS_RL}"
      - "NAMESPACE=poecilia"
    # depends_on:
    #   - socket-proxy
    # networks:
    #   - kop_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
