services:
  aria2:
    container_name: aria2
    ports:
      - ${ARIA2_LISTEN_PORT:-16888}:${ARIA2_LISTEN_PORT:-16888}
      - ${ARIA2_LISTEN_PORT:-16888}:${ARIA2_LISTEN_PORT:-16888}/udp
      - 16800:16800
    environment:
      - PUID=0
      - PGID=0
      - RPC_PORT=${ARIA2_RPC_PORT}
      - LISTEN_PORT=${ARIA2_LISTEN_PORT:-16888}
      - RPC_SECRET=${ARIA2_RPC_SECRET}
    volumes:
      - $DOCKER_DATA/aria2:/config
      - $PATH_MEDIA/downloads:/downloads
    restart: unless-stopped
    image: p3terx/aria2-pro:latest@sha256:086d1a37c586edb07ec0fb956bf9edd89d1d38d138ad5309ff96d510c8c9a011
    network_mode: bridge