services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.4@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/glance/config:/app/config
      - $DOCKER_DATA/glance/assets:/app/assets
    ports:
      - 42390:8080
