services:
  glance:
    container_name: glance
    image: glanceapp/glance:v0.8.2
    restart: unless-stopped
    volumes:
      - $DOCKER_DATA/glance/config:/app/config
      - $DOCKER_DATA/glance/assets:/app/assets
    ports:
      - 42390:8080
