services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-kiwiserver
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_DATA}/beszel-kiwiserver/beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
      # disk
      - /dev/sdb:/dev/sdb
      - /dev/sdc:/dev/sdc
      - /dev/sdd:/dev/sdd
      - /dev/sde:/dev/sde
      - /dev/sdf:/dev/sdf
      - /dev/sdg:/dev/sdg
      - /dev/sdh:/dev/sdh
      - /dev/sdi:/dev/sdi
      - /dev/nvme0:/dev/nvme0:ro
      - /dev/nvme1:/dev/nvme1:ro
      - /dev/nvme2:/dev/nvme2:ro
      - /dev/nvme3:/dev/nvme3:ro
      - /dev/nvme4:/dev/nvme4:ro
      - /dev/nvme5:/dev/nvme5:ro
      - /dev/nvme6:/dev/nvme6:ro
      # systemd
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    environment:
      LISTEN: 45876
      KEY: ${BESZEL_AGENT_KEY}
      TOKEN: ${BESZEL_AGENT_TOKEN}
      HUB_URL: ${BESZEL_HUB_URL}
    cap_add:
      - SYS_RAWIO # S.M.A.R.T
      - SYS_ADMIN # NVMe S.M.A.R.T.
