services:
  env-tester:
    image: nginx:1.31.0@sha256:800e7c98538c6bf725f5177e841aa720ae0ed1c378bbea368b6330bfe18a36b3
    restart: unless-stopped
    environment:
      - ddd=$DOCKER_DATA
      - HELLO=$DOCKER_DATA
    env_file:
      - ./compose.env
networks: {}
