services:
  env-tester:
    image: nginx:1.29.8@sha256:6e23479198b998e5e25921dff8455837c7636a67111a04a635cf1bb363d199dc
    restart: unless-stopped
    environment:
      - ddd=$DOCKER_DATA
      - HELLO=$DOCKER_DATA
    env_file:
      - ./compose.env
networks: {}
