version: '3.5'
services:
  drawio:
    image: jgraph/drawio:31.4.6@sha256:139b43305b77c46575d5af5dcc7b6c38dc7ea22f430fdfe954fb8f96926643e5
    container_name: drawio
    restart: unless-stopped
    ports:
      - 36711:8080
      #- 8443:8443
    #environment:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s