version: '3.5'
services:
  drawio:
    image: jgraph/drawio:30.0.2@sha256:63ba7ecd6722edc6fba7ee5285c37cf0e133205e5bf20d0a71646e76caddc1e7
    container_name: drawio
    restart: unless-stopped
    ports:
      - 36711:8080
      #- 8443:8443
    #environment:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s