version: '3.5'
services:
  drawio:
    image: jgraph/drawio:31.4.5@sha256:43104f0dd9e90f8d1e1eeb67944a45c9dc839373b9dda2fd0014f0b45f093570
    container_name: drawio
    restart: unless-stopped
    ports:
      - 36711:8080
      #- 8443:8443
    #environment:
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://domain:8080 || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 5
      start_period: 10s