
services:
  promtail:
    container_name: promtail
    restart: unless-stopped
    networks:
      - default
    ports:
      - 39180:9080
    volumes:
      - $DOCKER_DATA/logger/promtail/config:/config
      - /etc/localtime:/etc/localtime
      - $DOCKER_DATA/traefik_external/traefik/log/:/var/log/traefik:ro
    image: grafana/promtail:2.9.3@sha256:b338a29de45ef8ffa96f882f3a36306b1e61262b2a560ff523e0e2633cccbbc4
    command: -config.file=/config/promtail-config.yaml
  loki:
    container_name: loki
    restart: unless-stopped
    user: 0:0
    networks:
      - default
    volumes:
      - $DOCKER_DATA/logger/loki/config:/config
      - $DOCKER_DATA/logger/loki/tmp:/loki
      - /etc/localtime:/etc/localtime
    ports:
      - 30372:3100
    image: grafana/loki:2.9.17@sha256:c4a25af6f2709fa625d88ee5df494a332a85f30e9575854031667823ecc5be04
    command: -config.file=/config/loki-config.yaml

networks:
  default: