services:
  ems-pusher:
    image: ghcr.io/channinghe/ems2sns:latest@sha256:0384caa3f995ecf00679f68f3fe00e17eb30d58196ae1c17bb5f0ef6527ad9ed
    container_name: ems-pusher
    restart: unless-stopped
    user: ${GID_NIXOS_RL}:${GID_NIXOS_RL}
    network_mode: bridge
    environment:
      # Telegram Bot Configuration (REQUIRED)
      # - TELEGRAM_BOT_TOKEN=${TG_EMS_BOT_TOKEN}
      # - ALLOWED_USER_IDS=${TG_ALLOWED_USERS}
      # - ALLOWED_CHAT_IDS=${TG_ALLOWED_CHATS}
      # - POLL_INTERVAL=${POLL_INTERVAL:-1800}
      # - SUBSCRIPTIONS_FILE=${SUBSCRIPTIONS_FILE:-/app/data/subscriptions.json}
      # - PUSH_CHAT_IDS=${TG_PUSH_CHATS}
      - TZ=${LOCAL_TZ}
      - EMS2SNS_APP_LOG_LEVEL=debug
      # - KUAIDI100_KEY=${EMSPUSHER_KUAIDI100_KEY}
      # - KUAIDI100_CUSTOMER=${EMSPUSHER_KUAIDI100_CUSTOMER}
      #- SEVENTEEN_TRACK_TOKEN=${EMSPUSHER_SEVENTEEN_TRACK_TOKEN}
      - EMS2SNS_TELEGRAM_ENABLED=${EMS2SNS_TELEGRAM_ENABLED:-true}
      - EMS2SNS_TELEGRAM_BOT_TOKEN=${TG_EMS_BOT_TOKEN}
      - EMS2SNS_TELEGRAM_ALLOWED_USER_IDS=${TG_ALLOWED_USERS}
      - EMS2SNS_TELEGRAM_ALLOWED_CHAT_IDS=${TG_ALLOWED_CHATS}
      - EMS2SNS_TELEGRAM_PUSH_CHAT_IDS=${TG_PUSH_CHATS}
      #- EMS2SNS_DISCORD_ENABLED=${EMS2SNS_DISCORD_ENABLED:-false}
      #- EMS2SNS_DISCORD_BOT_TOKEN=${EMS2SNS_DISCORD_BOT_TOKEN:-}

      - EMS2SNS_TRACKING_POLL_INTERVAL=${EMS2SNS_TRACKING_POLL_INTERVAL:-1800s}
      - EMS2SNS_TRACKING_SEVENTEEN_TRACK_TOKEN=${EMSPUSHER_SEVENTEEN_TRACK_TOKEN}

      - EMS2SNS_STORAGE_PATH=/app/data/subs.json
    volumes:
      - $DOCKER_DATA/ems-pusher/data:/app/data
