services:

  traefik-kop-local:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    environment:
      - "REDIS_ADDR=${IP_POECILIA}:6379"
      - "DOCKER_HOST=tcp://socket-proxy:2375"
      - "KOP_HOSTNAME=${HOSTNAME:-generic}-local"
      - "BIND_IP=${IP_KIWISERVER}"
      - "NAMESPACE=poecilia"
    depends_on:
      - socket-proxy
    networks:
      - kop_net

  socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: socket-proxy
    networks:
      - kop_net
    environment:
      - CONTAINERS=1
      - POST=0
      - NODE=1
      - INFO=1
      #- PING=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # ports:
    #   - 2375:2375
    restart: always
    read_only: true
    tmpfs:
      - /run

networks:
  kop_net: