services:
  beszel:
    image: henrygd/beszel:latest@sha256:a849ad80814b6a1a3be665304dcace5d4854b3bed7bde4dd1227e8ce1b82d477
    container_name: beszel-hub
    restart: unless-stopped
    environment:
      APP_URL: https://beszel.${DOMAIN_INT}
    ports:
      - 38090:8090
    volumes:
      - ${DOCKER_DATA}/beszel/beszel-hub/data:/beszel_data
      - ${DOCKER_DATA}/beszel/beszel_socket:/beszel_socket
    networks:
      - traefik-poecilia_local_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.beszel-hub.rule=Host(`beszel.${DOMAIN_INT}`)"
      - "traefik.http.services.beszel-hub.loadbalancer.server.port=8090"
    # healthcheck:
    #   test: ['CMD', '/beszel', 'health', '--url', 'http://localhost:8090']
    #   interval: 120s
    #   start_period: 10s
    #   timeout: 5s

  beszel-agent:
    image: henrygd/beszel-agent:alpine@sha256:c6e925e00784b90eab68e2b813e4c722cf185f378d77e1129a97c064ca5fa7e4
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKER_DATA}/beszel/beszel-agent/data:/var/lib/beszel-agent
      - ${DOCKER_DATA}/beszel/beszel_socket:/beszel_socket
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # For systemd
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    devices:
      - /dev/nvme0:/dev/nvme0
      - /dev/nvme1:/dev/nvme1
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    environment:
      LISTEN: /beszel_socket/beszel.sock
      HUB_URL: http://localhost:38090
      TOKEN: ${BESZEL_AGENT_TOKEN}
      KEY: ${BESZEL_AGENT_KEY}
    # healthcheck:
    #   test: ['CMD', '/agent', 'health']
    #   interval: 120s

networks:
  traefik-poecilia_local_web:
    external: true
