services:
  komodo-apprise-alerter:
    image: foxxmd/komodo-apprise-alerter:0.0.5@sha256:724d38931b5311b5f4b6b124ae4f5080bc0748eef83b786927c5ec8531c0d12e
    restart: unless-stopped
    networks:
      - apprise
    depends_on:
      - apprise-api
    ports:
      - "37120:7000"
    environment:
      - TZ=${LOCAL_TZ}
      - APPRISE_ATTACH_SIZE=0 #optional
      - APPRISE_HOST=apprise-api:8000
      - APPRISE_STATELESS_URLS=${APPRISE_TG_URL}
      - APPRISE_PERSISTENT_KEYS=${APPRISE_PERSISTENT_KEYS}
  apprise-api:
    image: lscr.io/linuxserver/apprise-api:v1.4.1-ls239@sha256:e00fdea7e395502dc484b50ee9f781a04c8831a84dded3b58a746fa75e5cf76c
    container_name: apprise-api
    networks:
      - apprise
    environment:
      - PUID=${PM_RT_UID}
      - PGID=${PM_RT_GID}
      - TZ=${LOCAL_TZ}
      - APPRISE_ATTACH_SIZE=0 #optional
    volumes:
      - $DOCKER_DATA/apprise/apprise-api/config:/config
      #- $DOCKER_DATA/apprise/apprise-api/attachments:/attachments #optional
    ports:
      - 38030:8000
    restart: unless-stopped
networks:
  apprise: