version: "3.3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
 #   user: 568:568
    volumes:
      - $DOCKER_DATA/iyuuplus/config:/iyuu
      - $DOCKER_DATA/iyuuplus/data:/data
      - $DOCKER_DATA/iyuuplus/fake-group:/etc/group
    ports:
      - 38780:8780
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest@sha256:0de45e91a0f162c0750ce5f6c91f70c5ac645fe7e476a6c331da60d675f80a66
    network_mode: bridge
