version: "3.3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
 #   user: 568:568
    volumes:
      - $DOCKER_DATA/iyuuplus/config:/iyuu
      - $DOCKER_DATA/iyuuplus/data:/data
      - $DOCKER_DATA/iyuuplus/fake-group:/etc/group
    ports:
      - 38780:8780
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest@sha256:72981a789482482b0fe575e00233139d7462b1fc8edbb77d6805ccd7570a1430
    network_mode: bridge
