version: "3.3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
 #   user: 568:568
    volumes:
      - $DOCKER_DATA/iyuuplus/config:/iyuu
      - $DOCKER_DATA/iyuuplus/data:/data
      - $DOCKER_DATA/iyuuplus/fake-group:/etc/group
    ports:
      - 38780:8780
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest@sha256:011bd64c346150f1a6ff9f3680680cc20b815dad06df709a5f472b51fd82b9dc
    network_mode: bridge
