services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - 35924:8080
    volumes:
      - $DOCKER_DATA/open-webui/data:/app/backend/data
    restart: always
    networks:
      - traefik_external_public_web
    labels:
      traefik.enable: true
      traefik.public: true
      traefik.docker.network: traefik_external_public_web
      #-----
      traefik.http.routers.openwebui.rule: Host(`owb.${DOMAIN_CC}`) || Host(`owb.${DOMAIN_HISC}`)
      traefik.http.routers.openwebui.entrypoints: https, http
      traefik.http.services.openwebui.loadbalancer.server.port: 8080
      traefik.http.routers.openwebui.service: openwebui

networks:
  traefik_external_public_web:
    external: true