services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.12.3@sha256:cc84f2f5eb3c7734353701ccbaa24ed02dacb0d119114e50e4251e2005f3990a
    container_name: homepage
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=*
      # - PUID=${PM_RT_UID}
      # - PGID=${PM_RT_GID}
    volumes:
      - $DOCKER_DATA/homepage/config:/app/config
      - $DOCKER_DATA/homepage/icons:/app/public/icons
      - $DOCKER_DATA/homepage/images:/app/public/images
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 53300:3000
    restart: unless-stopped
    # labels:
    #   - diun.enable=true
networks: {}
