services:
  rdma-exporter:
    container_name: rdma-exporter
    network_mode: host
    restart: unless-stopped
    read_only: true
    volumes:
      - /sys/class/infiniband:/sys/class/infiniband:ro
    environment:
      - RDMA_EXPORTER_LOG_LEVEL=info
    image: ghcr.io/yuuki/rdma_exporter:0.4.1@sha256:3fdf050bc54ab64f2d683283edbaad8da2b07205f7ea4d223f32985f05527411
networks: {}
