services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.11.3@sha256:3e52522170dea0b587a976a7429f8fa6edf7be7d32cc3a1404b9087abb131f69
    container_name: open-webui
    ports:
      - 35924:8080
    volumes:
      - $DOCKER_DATA/open-webui/data:/app/backend/data
    restart: always
    networks:
      - traefik_external_public_web
    # labels:
    #   traefik.enable: true
    #   traefik.public: true
    #   traefik.docker.network: traefik_external_public_web
    #   #-----
    #   traefik.http.routers.openwebui.rule: Host(`owb.${DOMAIN_CC}`) || Host(`owb.${DOMAIN_HISC}`)
    #   traefik.http.routers.openwebui.entrypoints: https, http
    #   traefik.http.services.openwebui.loadbalancer.server.port: 8080
    #   traefik.http.routers.openwebui.service: openwebui

networks:
  traefik_external_public_web:
    external: true