version: "3.3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
 #   user: 568:568
    volumes:
      - $DOCKER_DATA/iyuuplus/config:/iyuu
      - $DOCKER_DATA/iyuuplus/data:/data
      - $DOCKER_DATA/iyuuplus/fake-group:/etc/group
    ports:
      - 38780:8780
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest@sha256:48bb90d8e294b1495a280a36e642214f4e177f4a54e2798ab0f857447e2ed320
    network_mode: bridge
