version: "3.3"
services:
  iyuuplus-dev:
    stdin_open: true
    tty: true
 #   user: 568:568
    volumes:
      - $DOCKER_DATA/iyuuplus/config:/iyuu
      - $DOCKER_DATA/iyuuplus/data:/data
      - $DOCKER_DATA/iyuuplus/fake-group:/etc/group
    ports:
      - 38780:8780
    container_name: IYUUPlus
    restart: always
    image: iyuucn/iyuuplus-dev:latest@sha256:6412a6ab84fac1e34a314a431eef16b0fe020e96a15ebc75c4351c6a5a594770
    network_mode: bridge
