services:
  mt-photos:
    image: mtphotos/mt-photos:latest@sha256:5b00f8fc87dad030b75c28a5f4322da273d1240cf7e244ad6be25b180a7bd2ff
    restart: unless-stopped
    ports:
      - 28063:8063
    environment:
      - GPID=5000
      - GUID=5000
      - TZ=${LOCAL_TZ}
      - API_AUTH_KEY=${MTPHOTOS_AI_API_AUTH_KEY}
    volumes:
      - ${DOCKER_DATA}/mt-photos/config:/config
      - ${PATH_BACKUP}/Photo/mtphoto:/upload
      - ${DOCKER_DATA}/mt-photos/mtphoto-fake-group:/etc/group
    labels:
      traefik.enable: true
      traefik.http.routers.mt-photos.rule: Host(`photos.${DOMAIN_INT}`)
      traefik.http.routers.mt-photos.entrypoints: websecure
      traefik.http.services.mt-photos.loadbalancer.server.port: 28063
      kop.namespace: poecilia
  mt-photos-ai:
    #port:8060
    container_name: mt-photos-ai
    stdin_open: true
    restart: unless-stopped
    environment:
      - AUTO_LOAD_TXT_MODAL=on
      - API_AUTH_KEY=${MTPHOTOS_AI_API_AUTH_KEY}
    image: mtphotos/mt-photos-ai:latest@sha256:1257f057837c863778903dc91eb5e71c88edba9ec2805bbc82937d318d51ab24
    
networks: {}
