services:
  ts-graphite-prometheus:
    image: ghcr.io/supporterino/truenas-graphite-to-prometheus:v2.2.1@sha256:60e7645f74a3243d7fb9e6a15c05ea3b4cddfd2bc7ba9e2b11321ce1d38286dd
    restart: unless-stopped
    ports:
      #graphite input
      - 39109:9109
      #prometheus output
      - 39108:9108