[[server]]
name = "nixos-rl"
tags = ["nixos-rl"]
[server.config]
address = "ws://10.1.200.7:8120"
send_mem_alerts = false

##

[[repo]]
name = "komodo-secrets-nixos-rl"
tags = ["nixos-rl"]
[repo.config]
server = "nixos-rl"
git_provider = "10.1.10.8:53110"
git_https = false
git_account = "ChanningHe"
repo = "channinghe/komodo-secrets"
path = "../komodo-secrets"