[[build]]
name = "caddy"
tags = ["builder"]
[build.config]
builder = "builder-kiwiserver"
version = "2.11.4"
auto_increment_version = false
image_name = "caddy"
linked_repo = "komodo-ops"
build_path = "build/caddy"
image_registry = [
  { domain = "registry.hub.docker.com", account = "channinghe" }
]

##

[[build]]
name = "komodo-periphery-sops"
tags = ["builder"]
[build.config]
builder = "builder-poecilia"
version = "2.3.1"
auto_increment_version = false
image_name = "komodo-periphery"
include_latest_tag = false
linked_repo = "komodo-ops"
build_path = "build/komodo-periphery-sops"
image_registry = [
  { domain = "registry.hub.docker.com", account = "channinghe" }
]
use_buildx = true
extra_args = [
  "--platform linux/amd64,linux/arm64",
  "--builder komodo-builder"
]
pre_build.command = """
docker buildx inspect komodo-builder >/dev/null 2>&1 \
  || docker buildx create \
    --name komodo-builder \
    --driver docker-container

docker buildx inspect --bootstrap komodo-builder
"""
pre_build.shell_mode = true
build_args = """
KOMODO_VERSION=[[$VERSION]]
"""