[[build]]
name = "caddy"
tags = ["builder"]
[build.config]
builder = "builder-poecilia"
version = "2.10.2"
auto_increment_version = false
image_name = "komodo-caddy"
linked_repo = "komodo-ops"
build_path = "build/caddy"
image_registry = [
  { domain = "registry.hub.docker.com", account = "channinghe" }
]

##

[[build]]
name = "komodo-periphery-sops"
tags = ["builder"]
[build.config]
builder = "builder-poecilia"
version = "2.1.2"
auto_increment_version = false
image_name = "komodo-periphery"
include_latest_tag = false
linked_repo = "komodo-ops"
build_path = "build/komodo-periphery-sops"
image_registry = [
  { domain = "registry.hub.docker.com", account = "channinghe" }
]
use_buildx = true
extra_args = [
  "--builder komodo-builder",
  "--platform linux/amd64,linux/arm64"
]
build_args = """
KOMODO_VERSION=[[$VERSION]]
"""